### ISSUE TITLE
Development Checklist 1 [Complete]

### ISSUE THREAD

**Issue by Redjumpman** [Redjumpman/Jumper-Cogs#2]
# Development Checklist

This list will attempt to serve as a way to monitor progress / check on what is being worked on
### Roulette*

**Description:** Casino style roulette game  
- [x] ~~Start ground work for code~~
- [x] ~~Create game system~~
- [x] ~~Add betting commands~~
- [x] ~~Store player bets~~
- [x] ~~Payout system~~
- [x] ~~Rules info~~
- [x] ~~Board diagram~~
- [x] ~~allow admins to change config settings~~
- [x] Testing **Placed on my repo. Will move to revision section after feedback/improvements**

---
### Blackjack

**Description:** Casino style roulette game  
- [x] ~~Start ground work for code~~
- [x] ~~Create game system~~
- [x] ~~Develop player system~~
- [x] ~~Add betting commands~~
- [x] ~~Store player(s) bets~~
- [x] ~~Payout system~~
- [x] ~~Testing~~

---
### Casino

**Description:** One file for all casino games   
- [x] ~~Start ground work for code~~
- [x] ~~Merge casino games~~
- [x] ~~Allow admins to change casino name~~
- [x] ~~Allow opening/closing of casino~~
- [x] ~~Create chip system~~
- [x] ~~Leader board ranking system~~
- [x] ~~Streamline info commands for casino~~
- [x] ~~Testing~~ **Placed on my repo. Will move to revision section after feedback**

---
### Heist

**Description:** Deepbot's Heist System  
- [x] ~~Start ground work for code~~
- [x] ~~Create game system~~
- [x] ~~Develop player system~~
- [x] ~~Add betting commands~~
- [x] ~~Add Config Commands~~
- [x] ~~Create bank tier system~~
- [x] ~~Create outcomes~~
- [x] ~~Organize commands~~ \*  
  ~~\- [ ] Add roles for players to pick~~ (moving this to an added feature, will not be in for release)
- [x] ~~Add separate points for banks~~
- [x] ~~Rules info~~
- [x] ~~Internal Testing~~*
- [x] ~~Testing~~ **Placed on my repo. Will move to revision section after feedback**

---
### Raffle system

**Description:** Players can buy tickets with points which increases their chance to win 
- [x] ~~Start code~~ 
- [x] ~~Create commands~~
- [x] ~~Create players dictionary to hold tickets~~
- [x] ~~Develop raffle system~~
- [x] ~~Testing~~\* **Placed on my repo. Will move to revision section after feedback**
## Cog Revisions

---
### Lottery
- [x] ~~add option to give away points to the winner~~

---
### Tibia
- [x] ~~add Hunted list / Friend list~~

---
### Shop
- [x] ~~Increase shop item limit from 50~~ (Can now have up to 100 items...ish)
- [x] change pending list output
- [x] ~~add toggle for sorting shop items by alphabetically or item price~~
- [x] ~~allow changing of the notify role~~
- [x] ~~add trading~~

*** Means this is currently being worked on**
