### ISSUE TITLE
New Road Map

### ISSUE THREAD

**Issue by Redjumpman** [Redjumpman/Jumper-Cogs#21]
# Off We Go...
This will be the new cog road map for Jumper-Cogs heading into 2017. I want to say I have really enjoyed making cogs for Red Bot, and I think that it is the best discord bot you can have. The Red community has really grown so I jumped on board as a cog creator in April-May of 2016 and I only see it getting bigger. Recently I got a really great opportunity to join a project unrelated to Discord bots. This is not an indication that I plan to stop making cogs or stop being a part of the Red community, but I will be sending out fewer updates and new content for a while. 

Before everything kicks off with my new project there are a few things I wanted to detail out in a road map for Jumper Cogs that will be completed before my hiatus. Thank you to everyone for all your support and for any server that might have enjoyed anything I created. Feel free to message me or post suggestions/bugs in a new issue. 

# These Old Dogs Still Gotta Few Tricks
### Casino (COMPLETE)

- [x] Optional payday function for casino like in Economy, but gives chips
- [x] Wipe a server based on name for bot owners with multiple servers
- [x] Logging to provide some level of moderation for those who use casino in a more serious manner
- [x] Implement casino membership levels as rewards granting access to games, reduced cooldowns, etc
- [x] Thresholds to limit winnings
- [x] New game
- [x] Auto updater for memberhsips

### Heist (Complete)

- [x] Templating to allow a bot owner to change the theme of heist. Similar system to how trivia can load different user created Q&A
- [x] Individual success for a heist will increase as you near the crew cap for that bank and reset when you meet the requirements for the next level up.
~~- [ ] Add items for purchase that can affect the heist. Example bullet proof vest will prevent death, but you will still go to jail on an outcome that would normally cause death.~~

### Pokemon (Complete)
- [x] Add learn set, a list of TM's/HM's that can be learned
- [x] Refactor the searches to optimize performance
- [x] Possibly change the output to an embed for some searches.

### Raffle (Pushed for V3 rewrite of Red Bot)
~~- [ ] Expand requirements
~~- [ ] Add more payment options
~~- [ ] Localization
~~- [ ] Refactoring

### Lottery (Complete Rewrite)  
- [x] Expand Requirements
- [x] Refactoring

# Out With The Old And In With The New

### Auction House
Cog that integrates with shop that allows you to post items for sale. Considering cross integration with servers that are pooled together. Example, you add server 1, 2, and 3 to a shard that shares an Auction House.

### MiniDnD
Really big cog that let's you play a scaled down version of DnD. Nearing testing phase!
