### ISSUE TITLE
Development Checklist 2

### ISSUE THREAD

**Issue by Redjumpman** [Redjumpman/Jumper-Cogs#7]
# Development Checklist

This list will attempt to serve as a way to monitor progress / check on what is being worked on.
If you have a cool idea you want added to the list send me a DM/PM on discord and I'll see if I can add it to my list.
### Pokemongo*

**Description:** Pokemongo data cog  
- [x] Pokemon Info
- [x] Fast attacks Info
- [x] Charged attacks info*
- [x] IV calculator  
- [ ] Closed Testing (Send cog to close friends)
- [ ] Send to git. Complete

---
## Cog Revisions

---
### Lottery  2.0 (Complete cog rewrite)
- [x] Multi-server support! Host lotteries on multiple servers with the same bot.
- [x] Nickname support.
- [x] Restrict lottery sign-up(for membership) by server role
- [x] Restrict lotteries to members or allow anyone on your server to participate
- [x] Can turn on auto-account freeze, will freeze a lottery membership who lost their server role
- [x] Frozen accounts can be reactivated with a user command if they have the set role
- [x] Can optionally set a timer for your lotteries. No need to manually end the lottery.
- [x] If restricted to lottery members, will @mention the set role to notify the lottery is on-going
- [x] Use dataIO instead of fileIO
- [x] Closed Testing (Send cog to close friends)
- [x] Send to git. Complete  
  **Note** Powerballs will come as a later update.
  ---
### Casino
- [ ] New game
- [ ] Membership calculator based on chip amount
- [ ] optionally restrict games based on casino membership
- [ ] Possible migration of roulette into casino 
- [x] Upgrade to using dataIO instead of fileIO
- [x] Fix blackjack issues. (FOR GOOD)
- [x] Change default timeout on blackjack to "Stay"

---
### Pokedex
- [ ] add learnset

---
### 
### Shop
- [x] Item quantities
- [ ] Upgrade to dataIO from fileIO

*** Means this is currently being worked on**
